// Renders tool-agnostic agent markdown (agents/<name>.md with YAML
// frontmatter) into the canonical Codex subagent TOML form and a sibling
// persona body used by the orchestrator's Windows runtime-injection path.
//
// Why two outputs?
//   - <name>.toml is what Codex on Mac/Linux reads natively.
//   - <name>.persona.md is the runtime-injection payload the
//     roster-orchestrator skill passes via `-c developer_instructions=…`
//     when Codex on Windows silently ignores the TOML (openai/codex#19399).
//     We emit it on every host so the orchestrator never branches on OS
//     when locating its source-of-truth — only the invocation path branches.
//     Remove the persona sidecar when openai/codex#19399 closes.
//
// Pure function. Mirrors src/lib/frontmatter.ts so audit.ts can render the
// source in-memory and byte-compare with the target (mutation-symmetry —
// see docs/learnings/2026-Q2/installer-mutations-need-drift-detector-mirror.md).

export class RosterAgentRenderError extends Error {
  public readonly field: string;
  constructor(message: string, field: string) {
    super(message);
    this.name = 'RosterAgentRenderError';
    this.field = field;
  }
}

export type CodexAgentSource = {
  name: string;
  description: string;
  body: string;
  model?: string;
  modelReasoningEffort?: string;
};

export type RenderedCodexAgent = {
  toml: string;
  personaBody: string;
};

const HEADER_COMMENT =
  '# Generated by roster install — DO NOT EDIT.\n' +
  '# Tracks openai/codex#19399 (Codex Windows subagent TOML ignored).\n' +
  '# Remove the Windows runtime-injection workaround when this issue closes.\n';

const REQUIRED_FIELDS = ['name', 'description'] as const;

export function parseAgentSource(content: string): CodexAgentSource {
  const fmMatch = content.match(/^---\n([\s\S]*?)\n---\n?/);
  if (!fmMatch) {
    throw new RosterAgentRenderError('Agent source has no YAML frontmatter block', 'frontmatter');
  }
  const fmBody = fmMatch[1] ?? '';
  const body = content.slice(fmMatch[0].length);
  const fields = parseFlatFrontmatter(fmBody);

  for (const required of REQUIRED_FIELDS) {
    if (!fields[required] || fields[required].length === 0) {
      throw new RosterAgentRenderError(`Required frontmatter field missing or empty: ${required}`, required);
    }
  }

  const name = fields['name'] as string;
  if (name.endsWith('.persona')) {
    throw new RosterAgentRenderError(
      `Agent name "${name}" must not end with ".persona" — collides with sidecar sibling`,
      'name',
    );
  }

  const legacyReasoning = fields['reasoning_effort'];
  const modelReasoningEffort = fields['model_reasoning_effort'] ?? legacyReasoning;

  return {
    name,
    description: fields['description'] as string,
    body: body.replace(/^[\n\r]+/, '').replace(/\s+$/, '') + '\n',
    model: fields['model'],
    modelReasoningEffort,
  };
}

function parseFlatFrontmatter(fm: string): Record<string, string> {
  const out: Record<string, string> = {};
  const lines = fm.split('\n');
  for (const raw of lines) {
    const line = raw.replace(/\r$/, '');
    if (line.length === 0) continue;
    if (line.startsWith('#')) continue;
    const match = line.match(/^([A-Za-z_][A-Za-z0-9_-]*):\s*(.*)$/);
    if (!match) {
      throw new RosterAgentRenderError(`Unparseable frontmatter line: ${line}`, 'frontmatter');
    }
    const key = match[1] as string;
    const rawValue = (match[2] ?? '').trim();
    out[key] = unquoteYamlScalar(rawValue, key);
  }
  return out;
}

function unquoteYamlScalar(raw: string, key: string): string {
  if (raw.length === 0) return '';
  const first = raw[0];
  if (first === '"' || first === "'") {
    if (raw.length < 2 || raw[raw.length - 1] !== first) {
      throw new RosterAgentRenderError(`Unterminated quoted scalar for ${key}: ${raw}`, key);
    }
    const inner = raw.slice(1, -1);
    if (first === '"') {
      return inner.replace(/\\"/g, '"').replace(/\\\\/g, '\\');
    }
    return inner;
  }
  return raw;
}

export function renderCodexAgentToml(source: string): RenderedCodexAgent {
  const parsed = parseAgentSource(source);
  return renderFromParsed(parsed);
}

function renderFromParsed(s: CodexAgentSource): RenderedCodexAgent {
  const lines: string[] = [];
  lines.push(HEADER_COMMENT.trimEnd());
  lines.push('');
  lines.push(`name = ${quoteBasic(s.name)}`);
  lines.push(`description = ${quoteBasic(s.description)}`);
  if (s.model !== undefined) lines.push(`model = ${quoteBasic(s.model)}`);
  if (s.modelReasoningEffort !== undefined) {
    lines.push(`model_reasoning_effort = ${quoteBasic(s.modelReasoningEffort)}`);
  }
  lines.push('');
  lines.push('developer_instructions = """');
  lines.push(escapeTripleBasic(s.body).replace(/\n$/, ''));
  lines.push('"""');
  lines.push('');
  return { toml: lines.join('\n'), personaBody: s.body };
}

function quoteBasic(value: string): string {
  return '"' + value.replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"';
}

// TOML multi-line basic strings `"""…"""` end on the first unescaped `"""`.
// Three consecutive double-quotes inside the body must be escaped. Everything
// else (including newlines, single quotes, embedded single double-quotes) is
// passed through unchanged.
function escapeTripleBasic(body: string): string {
  return body.replace(/"""/g, '\\"\\"\\"');
}
