import { mkdirSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { join, resolve } from 'node:path';
import { homedir } from 'node:os';
import chalk from 'chalk';
import {
  scheduleEntrySchema,
  flattenZodErrors,
  type ScheduleEntry,
  type InstallModeValue,
} from './schedule-schema.ts';
import {
  RosterError,
  EXIT_ERROR,
  codexPreflightError,
} from './errors.ts';
import { atomicWriteFile, readExistingSchedulesDoc, upsertEntryInDoc } from './schedule-yaml.ts';
import { deriveScheduleName, buildOrchestratorPrompt } from './schedule-install.ts';
import {
  runCodexPreflight,
  type PreflightResult,
  type PreflightFailure,
} from './codex-preflight.ts';
import {
  renderCronLine,
  upsertCronEntry,
  defaultCrontabIO,
  getMarkerStrings,
  type CrontabIO,
} from './codex-cron.ts';

export type CodexInstallOpts = {
  cwd: string;
  functionName: string;
  agent: string;
  plan: string;
  cron: string;
  name: string | undefined;
  installMode: InstallModeValue;
  dryRun: boolean;
  homeDir?: string;
  env?: NodeJS.ProcessEnv;
  crontabIO?: CrontabIO;
  codexBinaryPathOverride?: string;
};

export type CodexInstallAction = 'created' | 'updated' | 'noop-dry-run';

export type CodexInstallResult = {
  resolvedName: string;
  installMode: InstallModeValue;
  fieldsDocPath: string | null;
  fieldsDocContent: string | null;
  cronLine: string | null;
  logPath: string | null;
  schedulesYamlPath: string;
  action: CodexInstallAction;
  handoffMessage: string;
  workspacePath: string;
  attestation: { auth_mode: 'chatgpt'; env_policy: 'cleared'; codex_home: string };
};

const KEBAB_RE = /^[a-z0-9]+(-[a-z0-9]+)*$/;

function resolveCodexBinaryPath(env: NodeJS.ProcessEnv, override: string | undefined): string {
  if (override !== undefined && override !== '') return override;
  const fromEnv = env['ROSTER_CODEX_PATH'];
  if (fromEnv !== undefined && fromEnv !== '') return fromEnv;
  // Resolve via `command -v` (POSIX) so we get the binary the user's $PATH would pick.
  const r = spawnSync('/bin/sh', ['-c', 'command -v codex'], { encoding: 'utf8', env });
  if (r.status === 0) {
    const out = (r.stdout ?? '').trim();
    if (out.length > 0) return out;
  }
  throw new RosterError({
    header: `${chalk.red.bold('roster:')} codex binary not found on PATH`,
    body: '  Install codex CLI (https://developers.openai.com/codex) and ensure it is on your PATH.',
    remedy: '  Or pass ROSTER_CODEX_PATH=/abs/path/to/codex when invoking roster.',
    exitCode: EXIT_ERROR,
  });
}

export function renderCodexHandoffDoc(args: {
  name: string;
  cron: string;
  workspacePath: string;
  agent: string;
  plan: string;
}): string {
  const prompt = buildOrchestratorPrompt(args.agent, args.plan);
  return [
    `# Codex App Automation — ${args.name}`,
    '',
    'Codex Automations are created from a Codex thread via natural language. There is no TOML import API.',
    'Use the steps below to register this schedule in the Codex desktop app.',
    '',
    '## Field-by-field',
    '',
    '| Field | Value |',
    '|---|---|',
    `| Schedule name | \`${args.name}\` |`,
    `| Cron schedule | \`${args.cron}\` |`,
    `| Workspace path | \`${args.workspacePath}\` |`,
    '| Prompt | (see below) |',
    '',
    '## Prompt (copy verbatim)',
    '',
    '```',
    prompt,
    '```',
    '',
    '## Hand-off steps',
    '',
    '1. Open the Codex desktop app.',
    '2. Start a new thread.',
    `3. Paste the prompt above, then say: **"Schedule this for \`${args.cron}\` in workspace \`${args.workspacePath}\`."**`,
    '4. Codex will confirm the Automation; accept it.',
    '5. Verify in Codex → Automations that the new entry is active.',
    '',
    '---',
    '',
    '_Generated by `roster schedule install --tool codex` (ROS-35). Regenerate by re-running the same command._',
    '_Subscription-safety preflight passed: auth_mode=chatgpt, env=cleared, codex_home matches `$HOME/.codex`._',
    '',
  ].join('\n');
}

function renderHandoffMessage(args: {
  installMode: InstallModeValue;
  name: string;
  fieldsDocPath: string | null;
  cron: string;
  cronLine: string | null;
  logPath: string | null;
  action: CodexInstallAction;
}): string {
  const verb = args.action === 'created' ? 'Registered' : args.action === 'updated' ? 'Updated' : 'Would register';

  if (args.installMode === 'ui-handoff') {
    return [
      '',
      `${chalk.green('✓')} ${verb} codex schedule ${chalk.bold(args.name)} ${chalk.dim(`(cron: ${args.cron})`)}`,
      args.action === 'noop-dry-run'
        ? chalk.dim(`  Would write fields doc to: ${args.fieldsDocPath}`)
        : `  Fields doc: ${chalk.bold(args.fieldsDocPath ?? '')}`,
      '',
      chalk.bold('Next: paste into the Codex app'),
      `  1. Open the Codex desktop app`,
      `  2. Start a new thread`,
      `  3. Paste the prompt from the fields doc and say "Schedule this for ${args.cron}"`,
      `  4. Verify in Codex → Automations`,
      '',
      chalk.dim('Codex Automations are created in-thread; there is no TOML import API.'),
      '',
    ].join('\n');
  }

  // via-cron
  const markers = getMarkerStrings(args.name);
  const linesOut = [
    '',
    `${chalk.green('✓')} ${verb} codex schedule ${chalk.bold(args.name)} ${chalk.dim(`(cron: ${args.cron})`)}`,
    args.action === 'noop-dry-run'
      ? chalk.dim(`  Would append to crontab and write log to: ${args.logPath}`)
      : `  Crontab updated; log file: ${chalk.bold(args.logPath ?? '')}`,
    '',
    chalk.bold('Crontab block (managed):'),
    `  ${markers.begin}`,
    `  ${args.cronLine ?? ''}`,
    `  ${markers.end}`,
    '',
    chalk.dim('Inspect with `crontab -l`. To remove: `crontab -e` and delete the marker block.'),
    '',
  ];
  return linesOut.join('\n');
}

export function installCodexSchedule(opts: CodexInstallOpts): CodexInstallResult {
  const resolvedName = deriveScheduleName(opts.agent, opts.plan, opts.name);
  const workspacePath = resolve(opts.cwd);

  if (!KEBAB_RE.test(opts.functionName)) {
    throw new RosterError({
      header: `${chalk.red.bold('roster:')} invalid function name`,
      body: `  '${opts.functionName}' is not kebab-case (lowercase letters, digits, hyphens).`,
      remedy: `  Use a kebab-case function name (e.g., 'gtm', 'product-ops').`,
      exitCode: EXIT_ERROR,
    });
  }

  const homeDir = opts.homeDir ?? homedir();
  const env = opts.env ?? process.env;

  // ── Preflight ───────────────────────────────────────────────────────────
  const preflight: PreflightResult = runCodexPreflight({ homeDir, env });
  if (!preflight.ok) {
    throw codexPreflightError(preflight.failures);
  }

  // ── Build entry + validate ──────────────────────────────────────────────
  const entry: Record<string, unknown> = {
    name: resolvedName,
    agent: opts.agent,
    plan: opts.plan,
    cron: opts.cron,
    tool: 'codex',
    install_mode: opts.installMode,
    status: opts.installMode === 'via-cron' ? 'installed' : 'pending-ui-install',
    subscription_attestation: preflight.attestation,
  };

  const parsed = scheduleEntrySchema.safeParse(entry);
  if (!parsed.success) {
    const errs = flattenZodErrors(parsed.error);
    const first = errs[0]!;
    throw new RosterError({
      header: `${chalk.red.bold('roster:')} invalid schedule definition`,
      body: errs.map((e) => `  - ${e.path}: ${e.message}`).join('\n'),
      remedy: `  ${first.path === 'cron' ? 'Fix the --cron expression and re-run.' : 'Check kebab-case for agent/plan/name and re-run.'}`,
      exitCode: EXIT_ERROR,
    });
  }
  const validatedEntry: ScheduleEntry = parsed.data;

  // ── Paths ───────────────────────────────────────────────────────────────
  const schedulesYamlPath = join(workspacePath, 'roster', opts.functionName, 'schedules.yaml');
  const fieldsDocPath = opts.installMode === 'ui-handoff'
    ? join(workspacePath, '.roster', 'schedule-specs', `${resolvedName}.codex.fields.md`)
    : null;
  const logPath = opts.installMode === 'via-cron'
    ? join(workspacePath, 'logs', 'cron', `${resolvedName}.log`)
    : null;

  // ── Rendered content ────────────────────────────────────────────────────
  const fieldsDocContent = opts.installMode === 'ui-handoff'
    ? renderCodexHandoffDoc({
        name: resolvedName,
        cron: validatedEntry.cron,
        workspacePath,
        agent: validatedEntry.agent,
        plan: validatedEntry.plan,
      })
    : null;

  let cronLine: string | null = null;
  if (opts.installMode === 'via-cron') {
    const codexBinaryPath = resolveCodexBinaryPath(env, opts.codexBinaryPathOverride);
    cronLine = renderCronLine({
      cron: validatedEntry.cron,
      workspacePath,
      codexBinaryPath,
      prompt: buildOrchestratorPrompt(validatedEntry.agent, validatedEntry.plan),
      logPath: logPath!,
    });
  }

  // ── Dry-run early return (no writes, no mkdir, no crontab) ──────────────
  if (opts.dryRun) {
    return {
      resolvedName,
      installMode: opts.installMode,
      fieldsDocPath,
      fieldsDocContent,
      cronLine,
      logPath,
      schedulesYamlPath,
      action: 'noop-dry-run',
      handoffMessage: renderHandoffMessage({
        installMode: opts.installMode,
        name: resolvedName,
        fieldsDocPath,
        cron: validatedEntry.cron,
        cronLine,
        logPath,
        action: 'noop-dry-run',
      }),
      workspacePath,
      attestation: preflight.attestation,
    };
  }

  // ── YAML upsert ─────────────────────────────────────────────────────────
  const { doc } = readExistingSchedulesDoc(schedulesYamlPath);
  const { action } = upsertEntryInDoc(doc, validatedEntry);
  atomicWriteFile(schedulesYamlPath, doc.toString());

  // ── Mode-specific writes ────────────────────────────────────────────────
  if (opts.installMode === 'ui-handoff') {
    atomicWriteFile(fieldsDocPath!, fieldsDocContent!);
  } else {
    // Create logs/cron/ first so the cron redirect has a parent dir.
    const logDir = join(workspacePath, 'logs', 'cron');
    mkdirSync(logDir, { recursive: true });
    const io = opts.crontabIO ?? defaultCrontabIO();
    upsertCronEntry(io, resolvedName, cronLine!);
  }

  return {
    resolvedName,
    installMode: opts.installMode,
    fieldsDocPath,
    fieldsDocContent,
    cronLine,
    logPath,
    schedulesYamlPath,
    action,
    handoffMessage: renderHandoffMessage({
      installMode: opts.installMode,
      name: resolvedName,
      fieldsDocPath,
      cron: validatedEntry.cron,
      cronLine,
      logPath,
      action,
    }),
    workspacePath,
    attestation: preflight.attestation,
  };
}

export function formatPreflightFailures(failures: PreflightFailure[]): string {
  return failures
    .map((f) => `  - [${f.check}] expected ${f.expected}, got ${f.actual}\n      → ${f.remedy}`)
    .join('\n');
}
