import { mkdirSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { homedir } from 'node:os';
import chalk from 'chalk';
import {
  scheduleEntrySchema,
  flattenZodErrors,
  type ScheduleEntry,
  type InstallModeValue,
} from './schedule-schema.ts';
import {
  RosterError,
  EXIT_ERROR,
  codexPreflightError,
} from './errors.ts';
import { atomicWriteFile, readExistingSchedulesDoc, upsertEntryInDoc } from './schedule-yaml.ts';
import {
  assertFunctionDirWithinRoster,
  deriveScheduleName,
  buildOrchestratorPrompt,
} from './schedule-install.ts';
import {
  runCodexPreflight,
  type PreflightResult,
} from './codex-preflight.ts';
import {
  renderCronLine,
  upsertCronEntry,
  defaultCrontabIO,
  getMarkerStrings,
  cronMarkerId,
  resolveCodexBinaryPath,
  type CrontabIO,
} from './codex-cron.ts';
import { exitDirFor, eventsPathFor, logPathFor } from './cron-exit-log.ts';
import { functionsRegisteringSchedule } from './schedule-read.ts';

export type CodexInstallOpts = {
  cwd: string;
  functionName: string;
  agent: string;
  plan: string;
  cron: string;
  name: string | undefined;
  installMode: InstallModeValue;
  dryRun: boolean;
  homeDir?: string;
  env?: NodeJS.ProcessEnv;
  crontabIO?: CrontabIO;
  codexBinaryPathOverride?: string;
};

type CodexInstallAction = 'created' | 'updated' | 'noop-dry-run';

export type CodexInstallResult = {
  resolvedName: string;
  installMode: InstallModeValue;
  fieldsDocPath: string | null;
  fieldsDocContent: string | null;
  cronLine: string | null;
  logPath: string | null;
  schedulesYamlPath: string;
  action: CodexInstallAction;
  handoffMessage: string;
  workspacePath: string;
  attestation: { auth_mode: 'chatgpt'; env_policy: 'cleared'; codex_home: string };
};

function renderCodexHandoffDoc(args: {
  name: string;
  cron: string;
  workspacePath: string;
  functionName: string;
  agent: string;
  plan: string;
}): string {
  const prompt = buildOrchestratorPrompt(args.functionName, args.agent, args.plan, args.name);
  return [
    `# Codex App Automation — ${args.name}`,
    '',
    'Codex Automations are created from a Codex thread via natural language. There is no TOML import API.',
    'Use the steps below to register this schedule in the Codex desktop app.',
    '',
    '## Field-by-field',
    '',
    '| Field | Value |',
    '|---|---|',
    `| Schedule name | \`${args.name}\` |`,
    `| Cron schedule | \`${args.cron}\` |`,
    `| Workspace path | \`${args.workspacePath}\` |`,
    '| Prompt | (see below) |',
    '',
    '## Prompt (copy verbatim)',
    '',
    '```',
    prompt,
    '```',
    '',
    '## Hand-off steps',
    '',
    '1. Open the Codex desktop app.',
    '2. Start a new thread.',
    `3. Paste the prompt above, then say: **"Schedule this for \`${args.cron}\` in workspace \`${args.workspacePath}\`."**`,
    '4. Codex will confirm the Automation; accept it.',
    '5. Verify in Codex → Automations that the new entry is active.',
    '',
    '---',
    '',
    '_Generated by `roster schedule install --tool codex` (ROS-35). Regenerate by re-running the same command._',
    '_Subscription-safety preflight passed: auth_mode=chatgpt, env=cleared, codex_home matches `$HOME/.codex`._',
    '',
  ].join('\n');
}

function renderHandoffMessage(args: {
  installMode: InstallModeValue;
  name: string;
  markerId: string;
  fieldsDocPath: string | null;
  cron: string;
  cronLine: string | null;
  logPath: string | null;
  action: CodexInstallAction;
}): string {
  const verb = args.action === 'created' ? 'Registered' : args.action === 'updated' ? 'Updated' : 'Would register';

  if (args.installMode === 'ui-handoff') {
    return [
      '',
      `${chalk.green('✓')} ${verb} codex schedule ${chalk.bold(args.name)} ${chalk.dim(`(cron: ${args.cron})`)}`,
      args.action === 'noop-dry-run'
        ? chalk.dim(`  Would write fields doc to: ${args.fieldsDocPath}`)
        : `  Fields doc: ${chalk.bold(args.fieldsDocPath ?? '')}`,
      '',
      chalk.bold('Next: paste into the Codex app'),
      `  1. Open the Codex desktop app`,
      `  2. Start a new thread`,
      `  3. Paste the prompt from the fields doc and say "Schedule this for ${args.cron}"`,
      `  4. Verify in Codex → Automations`,
      '',
      chalk.dim('Codex Automations are created in-thread; there is no TOML import API.'),
      '',
    ].join('\n');
  }

  // via-cron
  const markers = getMarkerStrings(args.markerId);
  const linesOut = [
    '',
    `${chalk.green('✓')} ${verb} codex schedule ${chalk.bold(args.name)} ${chalk.dim(`(cron: ${args.cron})`)}`,
    args.action === 'noop-dry-run'
      ? chalk.dim(`  Would append to crontab and write log to: ${args.logPath}`)
      : `  Crontab updated; log file: ${chalk.bold(args.logPath ?? '')}`,
    '',
    chalk.bold('Crontab block (managed):'),
    `  ${markers.begin}`,
    `  ${args.cronLine ?? ''}`,
    `  ${markers.end}`,
    '',
    chalk.dim('Inspect with `crontab -l`. To remove: `crontab -e` and delete the marker block.'),
    '',
  ];
  return linesOut.join('\n');
}

export function installCodexSchedule(opts: CodexInstallOpts): CodexInstallResult {
  const resolvedName = deriveScheduleName(opts.agent, opts.plan, opts.name);
  const workspacePath = resolve(opts.cwd);
  const functionDir = assertFunctionDirWithinRoster(workspacePath, opts.functionName);

  const homeDir = opts.homeDir ?? homedir();
  const env = opts.env ?? process.env;

  // ── Preflight ───────────────────────────────────────────────────────────
  const preflight: PreflightResult = runCodexPreflight({ homeDir, env });
  if (!preflight.ok) {
    throw codexPreflightError(preflight.failures);
  }

  // ── Build entry + validate ──────────────────────────────────────────────
  const entry: Record<string, unknown> = {
    name: resolvedName,
    agent: opts.agent,
    plan: opts.plan,
    cron: opts.cron,
    tool: 'codex',
    install_mode: opts.installMode,
    status: opts.installMode === 'via-cron' ? 'installed' : 'pending-ui-install',
    subscription_attestation: preflight.attestation,
  };

  const parsed = scheduleEntrySchema.safeParse(entry);
  if (!parsed.success) {
    const errs = flattenZodErrors(parsed.error);
    const first = errs[0]!;
    throw new RosterError({
      header: `${chalk.red.bold('roster:')} invalid schedule definition`,
      body: errs.map((e) => `  - ${e.path}: ${e.message}`).join('\n'),
      remedy: `  ${first.path === 'cron' ? 'Fix the --cron expression and re-run.' : 'Check kebab-case for agent/plan/name and re-run.'}`,
      exitCode: EXIT_ERROR,
    });
  }
  const validatedEntry: ScheduleEntry = parsed.data;

  // ── Paths ───────────────────────────────────────────────────────────────
  const schedulesYamlPath = join(functionDir, 'schedules.yaml');
  const fieldsDocPath = opts.installMode === 'ui-handoff'
    ? join(workspacePath, '.roster', 'schedule-specs', `${resolvedName}.codex.fields.md`)
    : null;
  const logPath = opts.installMode === 'via-cron'
    ? logPathFor(workspacePath, opts.functionName, resolvedName)
    : null;
  const exitDir = opts.installMode === 'via-cron'
    ? exitDirFor(workspacePath, opts.functionName, resolvedName)
    : null;
  const markerId = cronMarkerId(opts.functionName, resolvedName);

  // ── Rendered content ────────────────────────────────────────────────────
  const fieldsDocContent = opts.installMode === 'ui-handoff'
    ? renderCodexHandoffDoc({
        name: resolvedName,
        cron: validatedEntry.cron,
        workspacePath,
        functionName: opts.functionName,
        agent: validatedEntry.agent,
        plan: validatedEntry.plan,
      })
    : null;

  let cronLine: string | null = null;
  if (opts.installMode === 'via-cron') {
    const codexBinaryPath = resolveCodexBinaryPath(env, opts.codexBinaryPathOverride);
    cronLine = renderCronLine({
      cron: validatedEntry.cron,
      workspacePath,
      codexBinaryPath,
      prompt: buildOrchestratorPrompt(opts.functionName, validatedEntry.agent, validatedEntry.plan, resolvedName),
      logPath: logPath!,
      exitDir: exitDir!,
      ...(validatedEntry.capture_events === true
        ? { eventsPath: eventsPathFor(workspacePath, opts.functionName, resolvedName) }
        : {}),
    });
  }

  // ── Dry-run early return (no writes, no mkdir, no crontab) ──────────────
  if (opts.dryRun) {
    return {
      resolvedName,
      installMode: opts.installMode,
      fieldsDocPath,
      fieldsDocContent,
      cronLine,
      logPath,
      schedulesYamlPath,
      action: 'noop-dry-run',
      handoffMessage: renderHandoffMessage({
        installMode: opts.installMode,
        name: resolvedName,
        markerId,
        fieldsDocPath,
        cron: validatedEntry.cron,
        cronLine,
        logPath,
        action: 'noop-dry-run',
      }),
      workspacePath,
      attestation: preflight.attestation,
    };
  }

  // ── YAML pre-flight: validate upsert would succeed (tool-mismatch guard) ──
  // We compute the upsert against an in-memory copy first so a YAML conflict
  // doesn't surface AFTER we've already mutated the user's crontab. The real
  // write happens last, after any side-effects on disk that could fail.
  const { doc } = readExistingSchedulesDoc(schedulesYamlPath, workspacePath);
  const { action } = upsertEntryInDoc(doc, validatedEntry);

  // ── Side-effect writes (crontab/fields doc) before YAML ─────────────────
  // Codex review impl-pass: YAML-first ordering meant a crontab write failure
  // would leave schedules.yaml claiming status=installed with no live cron
  // line. Side-effects now run before the YAML write — if any of them fail,
  // schedules.yaml stays consistent with the previous (un-touched) state.
  if (opts.installMode === 'ui-handoff') {
    atomicWriteFile(fieldsDocPath!, fieldsDocContent!, workspacePath);
  } else {
    // Create the per-fire exit dir at install time with a CHECKED mkdir (should-
    // fix 5): the runtime wrapper's `mkdir -p` can then never be the first attempt
    // on an unwritable path silently, and the dir's parent `logs/cron/<function>/`
    // (which also holds the log/events files) exists before the cron line's `>>`
    // redirect runs.
    mkdirSync(exitDir!, { recursive: true });
    const io = opts.crontabIO ?? defaultCrontabIO();
    // The legacy bare-name fallback carries the workspace-wide claimant list —
    // the installing function included, since its YAML entry is written LAST
    // (round-7 finding 2): once two functions claim the name, a bare marker can
    // no longer be attributed and the install refuses rather than rewriting the
    // other function's live block.
    upsertCronEntry(io, markerId, cronLine!, {
      id: resolvedName,
      registeredFunctions: [
        ...new Set([...functionsRegisteringSchedule(workspacePath, resolvedName), opts.functionName]),
      ],
    });
  }

  // ── YAML write last (commit) ────────────────────────────────────────────
  atomicWriteFile(schedulesYamlPath, doc.toString(), workspacePath);

  return {
    resolvedName,
    installMode: opts.installMode,
    fieldsDocPath,
    fieldsDocContent,
    cronLine,
    logPath,
    schedulesYamlPath,
    action,
    handoffMessage: renderHandoffMessage({
      installMode: opts.installMode,
      name: resolvedName,
      markerId,
      fieldsDocPath,
      cron: validatedEntry.cron,
      cronLine,
      logPath,
      action,
    }),
    workspacePath,
    attestation: preflight.attestation,
  };
}

