import { createHash } from 'node:crypto';
import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import YAML from 'yaml';
import { atomicWriteFile } from './schedule-yaml.ts';
import { scheduleFileSchema, type ScheduleEntry } from './schedule-schema.ts';
import {
  exitPathFor,
  logPathFor,
  readExitRecord,
  type ExitRecord,
} from './cron-exit-log.ts';
import {
  detectStale,
  findMostRecentRun,
  readStateMd,
  type StateLine,
} from './schedule-state.ts';

// ROS-42: synthesize error-class pending items from wrapper-level signals
// (`.exit` files, STALE detections). Idempotent: writes deterministic
// `pending/error-<id>.md` files where id = sha1(scheduleName + signalKey)
// so repeated runs of `roster pending sync` from SessionStart hooks + doctor
// don't duplicate entries.
//
// Out of scope: the orchestrator skill (which appends success/failed lines
// to state.md) and the in-LLM banner.sh hook (which surfaces the items this
// module writes). This module is the bridge between the two.

const DEFAULT_GRACE_MINUTES = 120;

export type PendingSyncResult = {
  written: Array<{ path: string; reason: 'failed-exit' | 'stale'; scheduleName: string }>;
  skipped: Array<{ path: string; reason: 'already-exists' }>;
  // Schedules we considered but had no signal worth surfacing.
  inspected: number;
};

export type PendingSyncOpts = {
  cwd: string;
  // Allow tests to clock-pin without monkey-patching Date.
  now?: Date;
  graceMinutes?: number;
  dryRun?: boolean;
};

type LoadedSchedule = {
  entry: ScheduleEntry;
  functionName: string;
};

function listFunctionDirs(rosterDir: string): string[] {
  try {
    return readdirSync(rosterDir, { withFileTypes: true })
      .filter((d) => d.isDirectory())
      .map((d) => d.name)
      .sort();
  } catch {
    return [];
  }
}

function loadAllSchedules(cwd: string): LoadedSchedule[] {
  const rosterRoot = join(cwd, 'roster');
  const out: LoadedSchedule[] = [];
  for (const fn of listFunctionDirs(rosterRoot)) {
    const yamlPath = join(rosterRoot, fn, 'schedules.yaml');
    let raw: string;
    try {
      raw = readFileSync(yamlPath, 'utf8');
    } catch {
      continue;
    }
    let parsed: unknown;
    try {
      parsed = YAML.parse(raw);
    } catch {
      continue;
    }
    const valid = scheduleFileSchema.safeParse(parsed);
    if (!valid.success) continue;
    for (const entry of valid.data.schedules) {
      out.push({ entry, functionName: fn });
    }
  }
  return out;
}

// Deterministic short id. We don't need cryptographic strength — just enough
// entropy to avoid collisions between different (schedule, signal) pairs and
// short enough to make `pending/error-<id>.md` filenames pleasant.
function shortId(scheduleName: string, signalKey: string): string {
  const h = createHash('sha1');
  h.update(scheduleName);
  h.update('\0');
  h.update(signalKey);
  return h.digest('hex').slice(0, 8);
}

function pendingDir(cwd: string, functionName: string): string {
  return join(cwd, 'roster', functionName, 'pending');
}

function pendingPath(cwd: string, functionName: string, id: string): string {
  return join(pendingDir(cwd, functionName), `error-${id}.md`);
}

function renderFailedExitItem(args: {
  schedule: LoadedSchedule;
  exit: ExitRecord;
  logPath: string;
  exitMtimeIso: string;
  pendingFilePath: string;
}): string {
  const { schedule, exit, logPath, exitMtimeIso, pendingFilePath } = args;
  const code = exit.exitCode === null ? '<unparseable>' : String(exit.exitCode);
  return [
    '---',
    `type: scheduled-fire-failure`,
    `schedule: ${schedule.entry.name}`,
    `function: ${schedule.functionName}`,
    `agent: ${schedule.entry.agent}`,
    `plan: ${schedule.entry.plan}`,
    `cron: '${schedule.entry.cron}'`,
    `exit_code: ${code}`,
    `exit_path: ${exit.exitPath}`,
    `log_path: ${logPath}`,
    `detected_at: '${new Date().toISOString()}'`,
    `fire_at: '${exitMtimeIso}'`,
    'severity: error',
    '---',
    '',
    `# Failed fire — \`${schedule.entry.name}\``,
    '',
    `The scheduled fire at ${exitMtimeIso} exited with code \`${code}\`. The`,
    `agent for \`${schedule.entry.agent}\`/\`${schedule.entry.plan}\` did not`,
    'complete normally.',
    '',
    `**Log:** \`${logPath}\``,
    '',
    '## Choose one',
    '',
    `- **Retry** — \`roster schedule run ${schedule.entry.name}\``,
    `- **Skip** — \`rm '${pendingFilePath}'\``,
    `- **Disable schedule** — \`roster schedule remove ${schedule.entry.name}\``,
    '',
    '_Auto-generated by `roster pending sync` (ROS-42). Re-running sync will not duplicate this item._',
    '',
  ].join('\n');
}

function renderStaleItem(args: {
  schedule: LoadedSchedule;
  expectedBeforeUtc: string;
  lastRun: StateLine | undefined;
}): string {
  const { schedule, expectedBeforeUtc, lastRun } = args;
  const lastRunLine = lastRun
    ? `${lastRun.timestamp} (status: ${lastRun.status})`
    : '(no record in state.md)';
  return [
    '---',
    `type: scheduled-fire-stale`,
    `schedule: ${schedule.entry.name}`,
    `function: ${schedule.functionName}`,
    `agent: ${schedule.entry.agent}`,
    `plan: ${schedule.entry.plan}`,
    `cron: '${schedule.entry.cron}'`,
    `expected_before: '${expectedBeforeUtc}'`,
    `last_run: '${lastRun?.timestamp ?? ''}'`,
    `detected_at: '${new Date().toISOString()}'`,
    'severity: warn',
    '---',
    '',
    `# Stale schedule — \`${schedule.entry.name}\``,
    '',
    `Expected a fresh fire by ${expectedBeforeUtc}, but the most recent`,
    `agent self-report is: ${lastRunLine}.`,
    '',
    'Possible causes:',
    '- The cron daemon (or Desktop Scheduled Task / Codex Automation) is not running',
    '- The schedule was disabled in the host app',
    '- The wrapper itself crashed before the agent could append to state.md',
    '',
    '## Choose one',
    '',
    `- **Verify cron is live** — \`roster doctor\` then \`crontab -l | grep ${schedule.entry.name}\``,
    `- **Fire manually** — \`roster schedule run ${schedule.entry.name}\``,
    `- **Disable schedule** — \`roster schedule remove ${schedule.entry.name}\``,
    '',
    '_Auto-generated by `roster pending sync` (ROS-42). Re-running sync will not duplicate this item._',
    '',
  ].join('\n');
}

export function syncPending(opts: PendingSyncOpts): PendingSyncResult {
  const cwd = resolve(opts.cwd);
  const now = opts.now ?? new Date();
  const graceMinutes = opts.graceMinutes ?? DEFAULT_GRACE_MINUTES;
  const dryRun = opts.dryRun ?? false;

  const written: PendingSyncResult['written'] = [];
  const skipped: PendingSyncResult['skipped'] = [];
  const schedules = loadAllSchedules(cwd);
  let inspected = 0;

  // Cache state.md per function to avoid re-reading on every schedule.
  const stateCache = new Map<string, ReturnType<typeof readStateMd>>();
  function stateFor(functionName: string) {
    const cached = stateCache.get(functionName);
    if (cached !== undefined) return cached;
    const path = join(cwd, 'roster', functionName, 'state.md');
    const result = readStateMd(path);
    stateCache.set(functionName, result);
    return result;
  }

  for (const schedule of schedules) {
    inspected++;
    // STALE detection works for both tools (Claude UI-handoff schedules can
    // still self-report via state.md), but the .exit channel is codex-only.
    const state = stateFor(schedule.functionName);
    const lastRun = findMostRecentRun(
      state.lines,
      schedule.functionName,
      schedule.entry.agent,
      schedule.entry.plan,
    );

    // Failed-exit signal (codex via-cron only; only modes that write .exit).
    let exitMtimeMs: number | undefined;
    if (schedule.entry.tool === 'codex' && schedule.entry.install_mode === 'via-cron') {
      const exitFile = exitPathFor(cwd, schedule.entry.name);
      const exitRecord = readExitRecord(exitFile);
      if (exitRecord !== null) {
        exitMtimeMs = exitRecord.mtimeMs;
        if (exitRecord.exitCode !== null && exitRecord.exitCode !== 0) {
          const exitMtimeIso = new Date(exitRecord.mtimeMs).toISOString();
          const id = shortId(schedule.entry.name, exitMtimeIso);
          const dst = pendingPath(cwd, schedule.functionName, id);
          if (existsSync(dst)) {
            skipped.push({ path: dst, reason: 'already-exists' });
          } else {
            const body = renderFailedExitItem({
              schedule,
              exit: exitRecord,
              logPath: logPathFor(cwd, schedule.entry.name),
              exitMtimeIso,
              pendingFilePath: dst,
            });
            if (!dryRun) atomicWriteFile(dst, body);
            written.push({ path: dst, reason: 'failed-exit', scheduleName: schedule.entry.name });
          }
        }
      }
    }

    // STALE signal — only when we have a lastRun to compare against (the
    // detectStale benign-default). For freshly-installed schedules with no
    // signals yet, schedules.yaml-mtime-based "registered but never ran"
    // would be the right check — out of scope for this PR.
    if (lastRun !== undefined) {
      const stale = detectStale({
        cronExpr: schedule.entry.cron,
        lastRun,
        lastFireMtimeMs: exitMtimeMs,
        now,
        graceMinutes,
      });
      if (stale.stale) {
        const id = shortId(schedule.entry.name, `stale:${stale.expectedBeforeUtc}`);
        const dst = pendingPath(cwd, schedule.functionName, id);
        if (existsSync(dst)) {
          skipped.push({ path: dst, reason: 'already-exists' });
        } else {
          const body = renderStaleItem({
            schedule,
            expectedBeforeUtc: stale.expectedBeforeUtc,
            lastRun,
          });
          if (!dryRun) atomicWriteFile(dst, body);
          written.push({ path: dst, reason: 'stale', scheduleName: schedule.entry.name });
        }
      }
    }
  }

  return { written, skipped, inspected };
}

// Helper for tests + the doctor section: how many of cwd's pending items are
// error-class (filename matches `error-<id>.md`). Used by render to badge the
// pending count.
export function countErrorPending(cwd: string): number {
  const root = join(cwd, 'roster');
  let count = 0;
  for (const fn of listFunctionDirs(root)) {
    const dir = pendingDir(cwd, fn);
    let entries: string[];
    try {
      entries = readdirSync(dir);
    } catch {
      continue;
    }
    for (const e of entries) {
      if (/^error-[a-f0-9]+\.md$/.test(e)) count++;
    }
  }
  return count;
}
