import { mkdirSync, readFileSync, writeFileSync, existsSync, renameSync, unlinkSync } from 'node:fs';
import { join, resolve, sep } from 'node:path';
import { randomBytes } from 'node:crypto';
import YAML from 'yaml';
import {
  scheduleEntrySchema,
  flattenZodErrors,
  SCHEDULES_YAML_VERSION,
  type ScheduleEntry,
} from './schedule-schema.ts';
import { RosterError, EXIT_ERROR, permissionError } from './errors.ts';
import chalk from 'chalk';

// Tracking issue for replacing UI hand-off with programmatic install:
// https://github.com/anthropics/claude-code/issues/41364
// When that issue ships a CLI for Desktop Scheduled Tasks, this module's
// renderFieldsDoc + renderHandoffMessage become a programmatic install call,
// and `status: 'pending-ui-install'` can transition directly to `'installed'`.

export type ClaudeInstallOpts = {
  cwd: string;
  functionName: string;
  agent: string;
  plan: string;
  cron: string;
  name: string | undefined;
  dryRun: boolean;
};

export type ClaudeInstallAction = 'created' | 'updated' | 'noop-dry-run';

export type ClaudeInstallResult = {
  resolvedName: string;
  fieldsDocPath: string;
  fieldsDocContent: string;
  schedulesYamlPath: string;
  action: ClaudeInstallAction;
  handoffMessage: string;
  workspacePath: string;
};

const DEFAULT_ALLOWED_TOOLS = [
  'Read',
  'Write',
  'Bash',
  'Task',
  'Edit',
  'Glob',
  'Grep',
] as const;

export function deriveScheduleName(agent: string, plan: string, override: string | undefined): string {
  if (override !== undefined && override !== '') return override;
  return `${agent}-${plan}`;
}

export function buildOrchestratorPrompt(agent: string, plan: string): string {
  return `Use the roster-orchestrator skill to run plan ${plan} for agent ${agent}`;
}

export function renderFieldsDoc(args: {
  name: string;
  cron: string;
  workspacePath: string;
  agent: string;
  plan: string;
}): string {
  const prompt = buildOrchestratorPrompt(args.agent, args.plan);
  const allowedTools = DEFAULT_ALLOWED_TOOLS.join(', ');
  return [
    `# Claude Desktop Scheduled Task — ${args.name}`,
    '',
    'Paste these fields into the **New local task** dialog in the Claude Desktop sidebar.',
    '',
    '## Field-by-field',
    '',
    '| Field | Value |',
    '|---|---|',
    `| Task name | \`${args.name}\` |`,
    `| Cron schedule | \`${args.cron}\` |`,
    `| Workspace path | \`${args.workspacePath}\` |`,
    '| Prompt | (see below) |',
    `| Allowed tools | \`${allowedTools}\` |`,
    '| MCP servers | (empty — add manually if your agent uses MCP) |',
    '',
    '## Prompt (copy verbatim)',
    '',
    '```',
    prompt,
    '```',
    '',
    '## Hand-off steps',
    '',
    '1. Open Claude Desktop.',
    '2. Click the Schedule icon in the sidebar.',
    '3. Click **New local task**.',
    '4. Fill in each field from the table above.',
    '5. Click **Save**. Your schedule is now active.',
    '',
    '---',
    '',
    '_Generated by `roster schedule install` (ROS-34). Regenerate by re-running the same command._',
    '_Tracking issue: [anthropics/claude-code#41364](https://github.com/anthropics/claude-code/issues/41364) — when this lands, this UI hand-off will be replaced by programmatic install._',
    '',
  ].join('\n');
}

export function renderHandoffMessage(args: {
  name: string;
  fieldsDocPath: string;
  cron: string;
  action: ClaudeInstallAction;
}): string {
  const verb = args.action === 'created' ? 'Registered' : args.action === 'updated' ? 'Updated' : 'Would register';
  const lines = [
    '',
    `${chalk.green('✓')} ${verb} schedule ${chalk.bold(args.name)} ${chalk.dim(`(cron: ${args.cron})`)}`,
    args.action === 'noop-dry-run'
      ? chalk.dim(`  Would write fields doc to: ${args.fieldsDocPath}`)
      : `  Fields doc: ${chalk.bold(args.fieldsDocPath)}`,
    '',
    chalk.bold('Next: paste into Claude Desktop'),
    `  1. Open Claude Desktop`,
    `  2. Click the ${chalk.bold('Schedule')} icon in the sidebar`,
    `  3. Click ${chalk.bold('New local task')}`,
    `  4. Fill in each field from ${chalk.bold('Field-by-field')} in the fields doc`,
    `  5. Click ${chalk.bold('Save')}`,
    '',
    chalk.dim('Tracking: anthropics/claude-code#41364 — once shipped, this becomes a one-step install.'),
    '',
  ];
  return lines.join('\n');
}

function atomicWriteFile(absPath: string, content: string): void {
  const dir = absPath.slice(0, absPath.lastIndexOf(sep));
  try {
    mkdirSync(dir, { recursive: true });
  } catch (err) {
    const e = err as NodeJS.ErrnoException;
    if (e.code === 'EACCES' || e.code === 'EPERM') throw permissionError(dir, e);
    throw err;
  }
  const tmp = `${absPath}.tmp-${randomBytes(6).toString('hex')}`;
  try {
    writeFileSync(tmp, content, { encoding: 'utf8', mode: 0o644 });
    renameSync(tmp, absPath);
  } catch (err) {
    try {
      unlinkSync(tmp);
    } catch {
      // best-effort cleanup
    }
    const e = err as NodeJS.ErrnoException;
    if (e.code === 'EACCES' || e.code === 'EPERM') throw permissionError(absPath, e);
    throw err;
  }
}

function readExistingSchedulesDoc(path: string): { doc: YAML.Document; existedBefore: boolean } {
  if (!existsSync(path)) {
    const doc = new YAML.Document({
      version: SCHEDULES_YAML_VERSION,
      schedules: [],
    });
    return { doc, existedBefore: false };
  }

  let content: string;
  try {
    content = readFileSync(path, 'utf8');
  } catch (err) {
    const e = err as NodeJS.ErrnoException;
    throw new RosterError({
      header: `${chalk.red.bold('roster:')} cannot read existing schedules.yaml`,
      body: `  ${e.code ?? e.message ?? 'unreadable'} reading ${path}`,
      remedy: `  Fix file permissions and re-run.`,
      exitCode: EXIT_ERROR,
    });
  }

  if (content.trim().length === 0) {
    const doc = new YAML.Document({
      version: SCHEDULES_YAML_VERSION,
      schedules: [],
    });
    return { doc, existedBefore: true };
  }

  const doc = YAML.parseDocument(content);
  if (doc.errors.length > 0) {
    const first = doc.errors[0]!;
    throw new RosterError({
      header: `${chalk.red.bold('roster:')} existing schedules.yaml is malformed`,
      body: `  ${first.message} (in ${path})`,
      remedy: `  Run ${chalk.bold('roster schedule validate')} for details, or fix the file by hand.`,
      exitCode: EXIT_ERROR,
    });
  }

  return { doc, existedBefore: true };
}

function upsertEntryInDoc(
  doc: YAML.Document,
  entry: ScheduleEntry,
): { action: 'created' | 'updated' } {
  // Ensure the version field is present and current.
  if (!doc.has('version')) {
    doc.set('version', SCHEDULES_YAML_VERSION);
  }

  let schedules = doc.get('schedules', true);
  if (schedules === undefined || schedules === null) {
    doc.set('schedules', []);
    schedules = doc.get('schedules', true);
  }

  if (!YAML.isSeq(schedules)) {
    throw new RosterError({
      header: `${chalk.red.bold('roster:')} existing schedules.yaml has the wrong shape`,
      body: `  Expected 'schedules' to be a list; got ${typeof schedules}.`,
      remedy: `  Run ${chalk.bold('roster schedule validate')} to inspect.`,
      exitCode: EXIT_ERROR,
    });
  }

  let existingIndex = -1;
  for (let i = 0; i < schedules.items.length; i++) {
    const item = schedules.items[i];
    if (YAML.isMap(item)) {
      const itemName = item.get('name');
      if (itemName === entry.name) {
        existingIndex = i;
        break;
      }
    }
  }

  const newMap = doc.createNode(entry);
  if (existingIndex >= 0) {
    schedules.items[existingIndex] = newMap;
    return { action: 'updated' };
  } else {
    schedules.add(newMap);
    return { action: 'created' };
  }
}

export function installClaudeSchedule(opts: ClaudeInstallOpts): ClaudeInstallResult {
  const resolvedName = deriveScheduleName(opts.agent, opts.plan, opts.name);
  const workspacePath = resolve(opts.cwd);

  const entry: Record<string, unknown> = {
    name: resolvedName,
    agent: opts.agent,
    plan: opts.plan,
    cron: opts.cron,
    tool: 'claude',
    install_mode: 'ui-handoff',
    status: 'pending-ui-install',
  };

  const parsed = scheduleEntrySchema.safeParse(entry);
  if (!parsed.success) {
    const errs = flattenZodErrors(parsed.error);
    const first = errs[0]!;
    throw new RosterError({
      header: `${chalk.red.bold('roster:')} invalid schedule definition`,
      body: errs.map((e) => `  - ${e.path}: ${e.message}`).join('\n'),
      remedy: `  ${first.path === 'cron' ? 'Fix the --cron expression and re-run.' : 'Check kebab-case for agent/plan/name and re-run.'}`,
      exitCode: EXIT_ERROR,
    });
  }
  const validatedEntry = parsed.data;

  // Re-validate functionName as kebab-case here. The schema doesn't see it
  // (functionName is a directory name, not a field), but it shapes the
  // filesystem layout, so we lock it to the same kebab rule the schema uses.
  const KEBAB_RE = /^[a-z0-9]+(-[a-z0-9]+)*$/;
  if (!KEBAB_RE.test(opts.functionName)) {
    throw new RosterError({
      header: `${chalk.red.bold('roster:')} invalid function name`,
      body: `  '${opts.functionName}' is not kebab-case (lowercase letters, digits, hyphens).`,
      remedy: `  Use a kebab-case function name (e.g., 'gtm', 'product-ops').`,
      exitCode: EXIT_ERROR,
    });
  }

  const fieldsDocPath = join(workspacePath, '.roster', 'schedule-specs', `${resolvedName}.claude.fields.md`);
  const schedulesYamlPath = join(workspacePath, 'roster', opts.functionName, 'schedules.yaml');

  const fieldsDocContent = renderFieldsDoc({
    name: resolvedName,
    cron: validatedEntry.cron,
    workspacePath,
    agent: validatedEntry.agent,
    plan: validatedEntry.plan,
  });

  if (opts.dryRun) {
    const handoffMessage = renderHandoffMessage({
      name: resolvedName,
      fieldsDocPath,
      cron: validatedEntry.cron,
      action: 'noop-dry-run',
    });
    return {
      resolvedName,
      fieldsDocPath,
      fieldsDocContent,
      schedulesYamlPath,
      action: 'noop-dry-run',
      handoffMessage,
      workspacePath,
    };
  }

  const { doc } = readExistingSchedulesDoc(schedulesYamlPath);
  const { action } = upsertEntryInDoc(doc, validatedEntry);

  atomicWriteFile(fieldsDocPath, fieldsDocContent);
  atomicWriteFile(schedulesYamlPath, doc.toString());

  const handoffMessage = renderHandoffMessage({
    name: resolvedName,
    fieldsDocPath,
    cron: validatedEntry.cron,
    action,
  });

  return {
    resolvedName,
    fieldsDocPath,
    fieldsDocContent,
    schedulesYamlPath,
    action,
    handoffMessage,
    workspacePath,
  };
}
