import { join, resolve } from 'node:path';
import { scheduleEntrySchema, flattenZodErrors } from './schedule-schema.ts';
import { RosterError, EXIT_ERROR, functionOutsideRosterError } from './errors.ts';
import { atomicWriteFile, readExistingSchedulesDoc, upsertEntryInDoc } from './schedule-yaml.ts';
import { functionDirWithinRoster } from './workspace-path.ts';
import chalk from 'chalk';

// The WRITE half of the round-11 finding-1 boundary, shared by both install
// paths (claude + codex). The schema never sees the function name — it is a
// directory, not a field — yet it shapes the filesystem layout, so it gets the
// same strict kebab rule the schema applies to agent/plan/name AND a
// resolved-path check against <workspace>/roster/. atomicWriteFile only proves
// the destination stays in the WORKSPACE, which `roster/<fn> -> ../archive`
// satisfies while leaving the registry.
export function assertFunctionDirWithinRoster(workspacePath: string, functionName: string): string {
  const dir = functionDirWithinRoster(workspacePath, functionName);
  if (dir === null) throw functionOutsideRosterError(functionName, workspacePath);
  return dir;
}

// Tracking issue for replacing UI hand-off with programmatic install:
// https://github.com/anthropics/claude-code/issues/41364
// When that issue ships a CLI for Desktop Scheduled Tasks, this module's
// renderFieldsDoc + renderHandoffMessage become a programmatic install call,
// and `status: 'pending-ui-install'` can transition directly to `'installed'`.

export type ClaudeInstallOpts = {
  cwd: string;
  functionName: string;
  agent: string;
  plan: string;
  cron: string;
  name: string | undefined;
  dryRun: boolean;
};

type ClaudeInstallAction = 'created' | 'updated' | 'noop-dry-run';

export type ClaudeInstallResult = {
  resolvedName: string;
  fieldsDocPath: string;
  fieldsDocContent: string;
  schedulesYamlPath: string;
  action: ClaudeInstallAction;
  handoffMessage: string;
  workspacePath: string;
};

const DEFAULT_ALLOWED_TOOLS = [
  'Read',
  'Write',
  'Bash',
  'Task',
  'Edit',
  'Glob',
  'Grep',
] as const;

export function deriveScheduleName(agent: string, plan: string, override: string | undefined): string {
  if (override !== undefined && override !== '') return override;
  return `${agent}-${plan}`;
}

// Contract: skills/roster-orchestrator/SKILL.md — the orchestrator parses
// <function>/<agent>, <plan>, and the schedule name from the prompt and refuses
// if agent or plan is missing. The schedule name is carried explicitly (round-6
// finding 3): two schedules in one function may legitimately share (agent,
// plan), so the fired prompt must name WHICH schedule fired — the orchestrator
// matches by name first and only falls back to the (agent, plan) pair for a
// legacy install, requiring uniqueness there. The agent is FUNCTION-QUALIFIED
// (round-7 finding 1): schedules.yaml entries store the BARE agent (the file is
// already function-scoped by its path), so the prompt must carry the function —
// it names WHICH roster/<function>/schedules.yaml to load, and it keeps a bare
// agent name duplicated across functions (gtm/sdr vs ops/sdr) resolvable. The
// skill strips the prefix and compares bare-to-bare against the registry.
export function buildOrchestratorPrompt(functionName: string, agent: string, plan: string, scheduleName: string): string {
  return `Use the roster-orchestrator skill to run plan ${plan} for agent ${functionName}/${agent} (schedule ${scheduleName})`;
}

export function renderFieldsDoc(args: {
  name: string;
  cron: string;
  workspacePath: string;
  functionName: string;
  agent: string;
  plan: string;
}): string {
  const prompt = buildOrchestratorPrompt(args.functionName, args.agent, args.plan, args.name);
  const allowedTools = DEFAULT_ALLOWED_TOOLS.join(', ');
  return [
    `# Claude Desktop Scheduled Task — ${args.name}`,
    '',
    'Paste these fields into the **New local task** dialog in the Claude Desktop sidebar.',
    '',
    '## Field-by-field',
    '',
    '| Field | Value |',
    '|---|---|',
    `| Task name | \`${args.name}\` |`,
    `| Cron schedule | \`${args.cron}\` |`,
    `| Workspace path | \`${args.workspacePath}\` |`,
    '| Prompt | (see below) |',
    `| Allowed tools | \`${allowedTools}\` |`,
    '| MCP servers | (empty — add manually if your agent uses MCP) |',
    '',
    '## Prompt (copy verbatim)',
    '',
    '```',
    prompt,
    '```',
    '',
    '## Hand-off steps',
    '',
    '1. Open Claude Desktop.',
    '2. Click the Schedule icon in the sidebar.',
    '3. Click **New local task**.',
    '4. Fill in each field from the table above.',
    '5. Click **Save**. Your schedule is now active.',
    '',
    '---',
    '',
    '_Generated by `roster schedule install` (ROS-34). Regenerate by re-running the same command._',
    '_Tracking issue: [anthropics/claude-code#41364](https://github.com/anthropics/claude-code/issues/41364) — when this lands, this UI hand-off will be replaced by programmatic install._',
    '',
  ].join('\n');
}

function renderHandoffMessage(args: {
  name: string;
  fieldsDocPath: string;
  cron: string;
  action: ClaudeInstallAction;
}): string {
  const verb = args.action === 'created' ? 'Registered' : args.action === 'updated' ? 'Updated' : 'Would register';
  const lines = [
    '',
    `${chalk.green('✓')} ${verb} schedule ${chalk.bold(args.name)} ${chalk.dim(`(cron: ${args.cron})`)}`,
    args.action === 'noop-dry-run'
      ? chalk.dim(`  Would write fields doc to: ${args.fieldsDocPath}`)
      : `  Fields doc: ${chalk.bold(args.fieldsDocPath)}`,
    '',
    chalk.bold('Next: paste into Claude Desktop'),
    `  1. Open Claude Desktop`,
    `  2. Click the ${chalk.bold('Schedule')} icon in the sidebar`,
    `  3. Click ${chalk.bold('New local task')}`,
    `  4. Fill in each field from ${chalk.bold('Field-by-field')} in the fields doc`,
    `  5. Click ${chalk.bold('Save')}`,
    '',
    chalk.dim('Tracking: anthropics/claude-code#41364 — once shipped, this becomes a one-step install.'),
    '',
  ];
  return lines.join('\n');
}

export function installClaudeSchedule(opts: ClaudeInstallOpts): ClaudeInstallResult {
  const resolvedName = deriveScheduleName(opts.agent, opts.plan, opts.name);
  const workspacePath = resolve(opts.cwd);
  const functionDir = assertFunctionDirWithinRoster(workspacePath, opts.functionName);

  const entry: Record<string, unknown> = {
    name: resolvedName,
    agent: opts.agent,
    plan: opts.plan,
    cron: opts.cron,
    tool: 'claude',
    install_mode: 'ui-handoff',
    status: 'pending-ui-install',
  };

  const parsed = scheduleEntrySchema.safeParse(entry);
  if (!parsed.success) {
    const errs = flattenZodErrors(parsed.error);
    const first = errs[0]!;
    throw new RosterError({
      header: `${chalk.red.bold('roster:')} invalid schedule definition`,
      body: errs.map((e) => `  - ${e.path}: ${e.message}`).join('\n'),
      remedy: `  ${first.path === 'cron' ? 'Fix the --cron expression and re-run.' : 'Check kebab-case for agent/plan/name and re-run.'}`,
      exitCode: EXIT_ERROR,
    });
  }
  const validatedEntry = parsed.data;

  const fieldsDocPath = join(workspacePath, '.roster', 'schedule-specs', `${resolvedName}.claude.fields.md`);
  const schedulesYamlPath = join(functionDir, 'schedules.yaml');

  const fieldsDocContent = renderFieldsDoc({
    name: resolvedName,
    cron: validatedEntry.cron,
    workspacePath,
    functionName: opts.functionName,
    agent: validatedEntry.agent,
    plan: validatedEntry.plan,
  });

  if (opts.dryRun) {
    const handoffMessage = renderHandoffMessage({
      name: resolvedName,
      fieldsDocPath,
      cron: validatedEntry.cron,
      action: 'noop-dry-run',
    });
    return {
      resolvedName,
      fieldsDocPath,
      fieldsDocContent,
      schedulesYamlPath,
      action: 'noop-dry-run',
      handoffMessage,
      workspacePath,
    };
  }

  const { doc } = readExistingSchedulesDoc(schedulesYamlPath, workspacePath);
  const { action } = upsertEntryInDoc(doc, validatedEntry);

  atomicWriteFile(fieldsDocPath, fieldsDocContent, workspacePath);
  atomicWriteFile(schedulesYamlPath, doc.toString(), workspacePath);

  const handoffMessage = renderHandoffMessage({
    name: resolvedName,
    fieldsDocPath,
    cron: validatedEntry.cron,
    action,
  });

  return {
    resolvedName,
    fieldsDocPath,
    fieldsDocContent,
    schedulesYamlPath,
    action,
    handoffMessage,
    workspacePath,
  };
}
