import { createHash } from 'node:crypto';
import { existsSync, readdirSync, readFileSync, statSync } from 'node:fs';
import { join, relative, sep } from 'node:path';
import { parse as parseYaml, stringify as stringifyYaml } from 'yaml';
import type { ToolKey } from '../tools.ts';
import { atomicWriteFile } from '../schedule-yaml.ts';
import { FOUNDER_SKILLS_LOCK_VERSION, isSafeSkillName } from './manifest-schema.ts';

export const LOCKFILE_NAME = 'founder-skills.lock';

export type LockedSkill = {
  name: string;
  ref: string;
  contentHash: string;
  tools: ToolKey[];
};

export type Lockfile = {
  version: number;
  source: string;
  skills: LockedSkill[];
};

export function lockfilePath(workspaceRoot: string): string {
  return join(workspaceRoot, LOCKFILE_NAME);
}

// Deterministic sha256 over a skill dir's file tree: sorted relative paths, each
// mixed with its bytes. Returns 'absent' when the dir doesn't exist so drift can
// distinguish "declared but not installed" from a real hash mismatch.
export function hashSkillDir(dir: string): string {
  if (!existsSync(dir)) return 'absent';
  const files: string[] = [];
  const walk = (d: string): void => {
    for (const name of readdirSync(d).sort()) {
      const full = join(d, name);
      const st = statSync(full);
      if (st.isDirectory()) walk(full);
      else if (st.isFile()) files.push(full);
    }
  };
  walk(dir);
  const hash = createHash('sha256');
  for (const f of files.sort()) {
    hash.update(relative(dir, f).split(sep).join('/'));
    hash.update('\0');
    hash.update(readFileSync(f));
    hash.update('\0');
  }
  return `sha256:${hash.digest('hex')}`;
}

export function readLockfile(workspaceRoot: string): Lockfile | null {
  const path = lockfilePath(workspaceRoot);
  if (!existsSync(path)) return null;
  try {
    const parsed = parseYaml(readFileSync(path, 'utf8')) as unknown;
    if (parsed === null || typeof parsed !== 'object') return null;
    const obj = parsed as Partial<Lockfile>;
    if (!Array.isArray(obj.skills)) return null;
    // Drop any entry whose name is not a safe kebab-case skill name. The
    // lockfile is on-disk and could be hand-edited; downstream code turns
    // `name` into a filesystem path (incl. rmSync during prune), so a name
    // containing `..` or `/` must never survive the read boundary.
    const skills = (obj.skills as unknown[]).filter(
      (s): s is LockedSkill =>
        s !== null && typeof s === 'object' && isSafeSkillName((s as { name?: unknown }).name),
    );
    return {
      version: typeof obj.version === 'number' ? obj.version : FOUNDER_SKILLS_LOCK_VERSION,
      source: typeof obj.source === 'string' ? obj.source : '',
      skills,
    };
  } catch {
    return null;
  }
}

export function writeLockfile(workspaceRoot: string, lock: Lockfile): void {
  const ordered: Lockfile = {
    version: lock.version,
    source: lock.source,
    skills: [...lock.skills].sort((a, b) => a.name.localeCompare(b.name)),
  };
  const banner = '# Generated by `roster skills sync`. Do not edit by hand.\n';
  atomicWriteFile(lockfilePath(workspaceRoot), banner + stringifyYaml(ordered));
}
