import { copyFileSync, existsSync, mkdirSync, readFileSync, renameSync, writeFileSync, chmodSync, unlinkSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { randomBytes } from 'node:crypto';
import type { MigrationPlan, ScheduleInstallCmd } from './plan.ts';
import {
  MANIFEST_VERSION,
  decideFileAction,
  manifestPathFor,
  readManifest,
  safeFileSha256,
  sourceHashFor,
  writeManifest,
  type Manifest,
  type ManifestFileEntry,
} from './manifest.ts';

export type ExecuteOptions = {
  dryRun: boolean;
  forceResync: boolean;
  /** Injectable clock for deterministic test output. */
  clock?: () => Date;
};

export type FileOpResult =
  | { kind: 'written'; src: string; dest: string }
  | { kind: 'noop'; src: string; dest: string; reason: string }
  | { kind: 'skipped'; src: string; dest: string; reason: string }
  | { kind: 'collided-renamed'; src: string; dest: string; finalDest: string };

export type ExecuteReport = {
  blockersHit: boolean;
  fileResults: ReadonlyArray<FileOpResult>;
  installScriptPath: string | null;
  installScriptContent: string;
  reportPath: string | null;
  manifestPath: string | null;
  generatedAtUtc: string;
};

function nowUtcIso(clock: ExecuteOptions['clock']): string {
  const d = clock ? clock() : new Date();
  return d.toISOString();
}

function timestampSlug(clock: ExecuteOptions['clock']): string {
  const d = clock ? clock() : new Date();
  const pad = (n: number): string => String(n).padStart(2, '0');
  return `${d.getUTCFullYear()}-${pad(d.getUTCMonth() + 1)}-${pad(d.getUTCDate())}-${pad(d.getUTCHours())}${pad(d.getUTCMinutes())}`;
}

function atomicWriteFile(absPath: string, content: string, mode = 0o644): void {
  const dir = dirname(absPath);
  mkdirSync(dir, { recursive: true });
  const tmp = `${absPath}.tmp-${randomBytes(6).toString('hex')}`;
  try {
    writeFileSync(tmp, content, { encoding: 'utf8', mode });
    renameSync(tmp, absPath);
  } catch (err) {
    try {
      unlinkSync(tmp);
    } catch {
      // best-effort
    }
    throw err;
  }
}

function resolveCollidedDest(destPath: string): string {
  if (!existsSync(destPath)) return destPath;
  const ext = destPath.includes('.') ? destPath.slice(destPath.lastIndexOf('.')) : '';
  const base = ext ? destPath.slice(0, -ext.length) : destPath;
  for (let n = 2; n < 100; n++) {
    const candidate = `${base}-r${n}${ext}`;
    if (!existsSync(candidate)) return candidate;
  }
  throw new Error(`migrate: too many collisions resolving ${destPath}`);
}

export function renderInstallScript(plan: MigrationPlan, generatedAtUtc: string): string {
  const lines: string[] = [
    '#!/usr/bin/env bash',
    `# Generated by roster migrate from-agent-team at ${generatedAtUtc}`,
    `# Source: ${plan.sourceDir}`,
    `# Destination: ${plan.destWorkspace}`,
    '#',
    '# Review each line, then run:',
    `#   bash $(basename "$0")`,
    'set -euo pipefail',
    '',
  ];

  const claudeLines = plan.scheduleInstalls.filter((s) => s.tool === 'claude');
  const codexLines = plan.scheduleInstalls.filter((s) => s.tool === 'codex');

  if (claudeLines.length > 0) {
    lines.push('# Claude schedules');
    for (const s of claudeLines) lines.push(s.rendered);
    lines.push('');
  }

  if (codexLines.length > 0) {
    lines.push('# Codex schedules (default = UI hand-off via Codex desktop app)');
    lines.push('# Add `--via cron` to a line below for programmatic install instead.');
    for (const s of codexLines) lines.push(s.rendered);
    lines.push('');
  }

  if (plan.unmappedWrappers.length > 0) {
    lines.push('# Unmapped wrappers — could not determine function/agent/plan');
    for (const u of plan.unmappedWrappers) {
      lines.push(`# TODO  ${u.basename}  (cron: ${u.cron}, source: ${u.wrapperPath})`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

function copyFileWithManifest(args: {
  src: string;
  dest: string;
  manifestEntry: ManifestFileEntry | undefined;
  forceResync: boolean;
  generatedAtUtc: string;
  dryRun: boolean;
  newManifestEntries: ManifestFileEntry[];
}): FileOpResult {
  const { src, dest, manifestEntry, forceResync, generatedAtUtc, dryRun, newManifestEntries } = args;
  if (!existsSync(src)) {
    return { kind: 'skipped', src, dest, reason: 'source-not-found' };
  }
  const srcSha = safeFileSha256(src);
  if (srcSha === null) {
    return { kind: 'skipped', src, dest, reason: 'source-unreadable' };
  }

  const decision = decideFileAction({
    srcPath: src,
    destPath: dest,
    srcSha,
    manifestEntry,
    forceResync,
  });

  if (decision.kind === 'noop') {
    newManifestEntries.push({ src, dest, srcSha256: srcSha, copiedAtUtc: manifestEntry?.copiedAtUtc ?? generatedAtUtc });
    return { kind: 'noop', src, dest, reason: decision.reason };
  }
  if (decision.kind === 'skip') {
    if (manifestEntry !== undefined) newManifestEntries.push(manifestEntry);
    return { kind: 'skipped', src, dest, reason: decision.reason };
  }

  // decision.kind === 'write'
  if (dryRun) {
    return { kind: 'written', src, dest };
  }

  mkdirSync(dirname(dest), { recursive: true });
  copyFileSync(src, dest);
  newManifestEntries.push({ src, dest, srcSha256: srcSha, copiedAtUtc: generatedAtUtc });
  return { kind: 'written', src, dest };
}

function copyPendingWithCollision(args: {
  src: string;
  dest: string;
  manifestEntry: ManifestFileEntry | undefined;
  forceResync: boolean;
  generatedAtUtc: string;
  dryRun: boolean;
  newManifestEntries: ManifestFileEntry[];
}): FileOpResult {
  const { dest, manifestEntry, dryRun } = args;
  // If dest exists AND we have no manifest entry pointing at it, treat as collision and rename.
  if (existsSync(dest) && manifestEntry === undefined) {
    const finalDest = resolveCollidedDest(dest);
    if (dryRun) {
      return { kind: 'collided-renamed', src: args.src, dest, finalDest };
    }
    mkdirSync(dirname(finalDest), { recursive: true });
    copyFileSync(args.src, finalDest);
    const srcSha = safeFileSha256(args.src) ?? '';
    args.newManifestEntries.push({ src: args.src, dest: finalDest, srcSha256: srcSha, copiedAtUtc: args.generatedAtUtc });
    return { kind: 'collided-renamed', src: args.src, dest, finalDest };
  }
  return copyFileWithManifest(args);
}

export function executeMigration(plan: MigrationPlan, opts: ExecuteOptions): ExecuteReport {
  const generatedAtUtc = nowUtcIso(opts.clock);
  const fileResults: FileOpResult[] = [];

  if (plan.blockers.length > 0) {
    return {
      blockersHit: true,
      fileResults,
      installScriptPath: null,
      installScriptContent: '',
      reportPath: null,
      manifestPath: null,
      generatedAtUtc,
    };
  }

  const sourceHash = sourceHashFor(plan.sourceDir);
  const manifestPath = manifestPathFor(plan.destWorkspace, sourceHash);
  const previousManifest = readManifest(manifestPath);
  const lookup = new Map<string, ManifestFileEntry>();
  if (previousManifest !== null) {
    for (const e of previousManifest.files) lookup.set(`${e.src}->${e.dest}`, e);
  }

  const newManifestEntries: ManifestFileEntry[] = [];

  // 1. Pending HITL moves (collision-aware)
  for (const m of plan.pendingMoves) {
    fileResults.push(
      copyPendingWithCollision({
        src: m.srcPath,
        dest: m.destPath,
        manifestEntry: lookup.get(`${m.srcPath}->${m.destPath}`),
        forceResync: opts.forceResync,
        generatedAtUtc,
        dryRun: opts.dryRun,
        newManifestEntries,
      }),
    );
  }

  // 2. Log copies
  for (const lc of plan.logCopies) {
    for (const file of lc.files) {
      const dest = join(lc.destDir, file.relSrc);
      fileResults.push(
        copyFileWithManifest({
          src: file.absSrc,
          dest,
          manifestEntry: lookup.get(`${file.absSrc}->${dest}`),
          forceResync: opts.forceResync,
          generatedAtUtc,
          dryRun: opts.dryRun,
          newManifestEntries,
        }),
      );
    }
  }

  // 3. .env copy with explicit mode 0o600
  if (plan.envCopy !== null) {
    const { src, dest } = plan.envCopy;
    const srcSha = safeFileSha256(src);
    const entry = lookup.get(`${src}->${dest}`);
    if (srcSha === null) {
      fileResults.push({ kind: 'skipped', src, dest, reason: 'source-unreadable' });
    } else {
      const decision = decideFileAction({ srcPath: src, destPath: dest, srcSha, manifestEntry: entry, forceResync: opts.forceResync });
      if (decision.kind === 'write') {
        if (opts.dryRun) {
          fileResults.push({ kind: 'written', src, dest });
        } else {
          const body = readFileSync(src);
          mkdirSync(dirname(dest), { recursive: true });
          atomicWriteFile(dest, body.toString('utf8'), 0o600);
          chmodSync(dest, 0o600);
          newManifestEntries.push({ src, dest, srcSha256: srcSha, copiedAtUtc: generatedAtUtc });
          fileResults.push({ kind: 'written', src, dest });
        }
      } else if (decision.kind === 'noop') {
        newManifestEntries.push({ src, dest, srcSha256: srcSha, copiedAtUtc: entry?.copiedAtUtc ?? generatedAtUtc });
        fileResults.push({ kind: 'noop', src, dest, reason: decision.reason });
      } else {
        if (entry !== undefined) newManifestEntries.push(entry);
        fileResults.push({ kind: 'skipped', src, dest, reason: decision.reason });
      }
    }
  }

  // 4. Install script
  const ts = timestampSlug(opts.clock);
  const installScriptPath = join(plan.destWorkspace, '.roster', 'migration-scripts', `install-schedules-${ts}.sh`);
  const installScriptContent = renderInstallScript(plan, generatedAtUtc);

  if (!opts.dryRun) {
    atomicWriteFile(installScriptPath, installScriptContent, 0o755);
    chmodSync(installScriptPath, 0o755);
  }

  // 5. Manifest write — only on live execution
  if (!opts.dryRun) {
    const manifest: Manifest = {
      version: MANIFEST_VERSION,
      sourceDir: plan.sourceDir,
      sourceHash,
      migratedAt: generatedAtUtc,
      files: dedupeEntries(newManifestEntries),
    };
    writeManifest(manifestPath, manifest);
  }

  return {
    blockersHit: false,
    fileResults,
    installScriptPath,
    installScriptContent,
    reportPath: null, // set by command-level renderer; execute returns the in-memory content
    manifestPath,
    generatedAtUtc,
  };
}

function dedupeEntries(entries: ReadonlyArray<ManifestFileEntry>): ManifestFileEntry[] {
  const seen = new Map<string, ManifestFileEntry>();
  for (const e of entries) seen.set(`${e.src}->${e.dest}`, e);
  return [...seen.values()].sort((a, b) => a.src.localeCompare(b.src));
}

// Re-export for command-level coordination
export type ExecuteScheduleSummary = {
  claudeReady: number;
  codexBlocked: number;
  unmapped: number;
};

export function summarizeSchedules(plan: MigrationPlan): ExecuteScheduleSummary {
  const claudeReady = plan.scheduleInstalls.filter((s: ScheduleInstallCmd) => !s.blocked).length;
  const codexBlocked = plan.scheduleInstalls.filter((s: ScheduleInstallCmd) => s.blocked).length;
  return { claudeReady, codexBlocked, unmapped: plan.unmappedWrappers.length };
}
